<a href="https://colab.research.google.com/github/nualpair/multivariate/blob/main/Function_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#function



```python
def function_name(Input_):
  do_something with_Input_to produce_output_
  return_output_
```



function มีส่วนสำคัญ 4 ส่วน


1.บอก python ว่าเราจะเขียนฟังก์ชันชื่ออะไร def function_name(): (ขาดไม่ได้)


2.กำหนดตัวแปรที่จะเป็น input *input* (ขาดได้)


3.ส่วนประมวลผล do_something with *input* to get *output* (ขาดไม่ได้)


4.ส่วน output return output (ขาดได้)

เราใช้ เว้นวรรค(indent) เพื่อบอกขอบเขตของ code

###สร้างฟังก์ชั่น

In [15]:
def print_name(name,surname,ID): #inputสามารถมีกี่ตัวหรือไม่มีก็ได้
  st = f'ชื่อ {name} นามสกุล {surname} ID {ID}'
  return st
print ('outside function')

outside function


###เรียกใช้ฟังก์ชั่น

In [16]:
print_name('กิตติมา','อุปสุข','623021040-9')

'ชื่อ กิตติมา นามสกุล อุปสุข ID 623021040-9'

In [17]:
output_string = print_name('กิตติมา','อุปสุข','623021040-9')
print(output_string)

ชื่อ กิตติมา นามสกุล อุปสุข ID 623021040-9


In [18]:
def print_name2(surname,ID,name) :
  st = f'ชื่อ {name} นามสกุล {surname} ID {ID}'
  print(st)

##ฟังก์ชั่นที่ไม่จำเป็นต้องมี output

In [19]:
op2 = print_name2('กิตติมา','อุปสุข','623021040-9')

ชื่อ 623021040-9 นามสกุล กิตติมา ID อุปสุข


In [20]:
print(op2)

None


##ฟังก์ชั่นไม่จำเป็นต้องมี input

In [21]:
def Pi():
  return 3.14159265359

In [22]:
#คำนวณพื้นที่วงกลมที่มีขนาดเส้นผ่านศุนย์กลางเท่ากับ3
Pi()*(1.5**2)

7.0685834705775

In [23]:
def print_my_name():
  print('นวลแพร')

In [24]:
print_my_name()

นวลแพร


##input ของ function ใน python มีสองแบบ

1.input ที่จำเป็นต้องใส่ (มีค่า default)

2.input ที่ไม่จำเป็นต้องใส่

In [25]:
def print_2lines_default(name,surname,ID,grade='f'):
  st = f'ชื่อ {name} นามสกุล {surname} รหัส {ID}'
  print(st)
  st2=f'เกรดวิชา Multivariate >>> {grade}'
  print(st2)

In [26]:
print_2lines_default('นวลแพร','พนาวัฒนวงศ์','623020525-0')

ชื่อ นวลแพร นามสกุล พนาวัฒนวงศ์ รหัส 623020525-0
เกรดวิชา Multivariate >>> f


In [27]:
print_2lines_default('นวลแพร','พนาวัฒนวงศ์','623020525-0','A')

ชื่อ นวลแพร นามสกุล พนาวัฒนวงศ์ รหัส 623020525-0
เกรดวิชา Multivariate >>> A


##HW03 ให้เขียน function คำนวณจำนวนวินาทีจากเวลาต่อไปนี้

'14-15-31'

'13-00-01'

'05-49-44'

'00-00-16'

และ print ให้สวยงาม



In [28]:
def time(t):
  j3=  int (t.split('-')[0])*3600
  k3= int (t.split('-')[1])*60
  n3 = int (t.split('-')[2])
  tt = j3+k3+n3
  print("แปลงเป็นวินาทีได้เท่ากับ",tt," วินาที")

In [29]:
time('14-15-31') 

แปลงเป็นวินาทีได้เท่ากับ 51331  วินาที


In [30]:
time('13-00-01') 

แปลงเป็นวินาทีได้เท่ากับ 46801  วินาที


In [31]:
time('05-49-44') 

แปลงเป็นวินาทีได้เท่ากับ 20984  วินาที


In [32]:
time('00-00-16') 

แปลงเป็นวินาทีได้เท่ากับ 16  วินาที


Numply -> package สำหรับการจัดการกับ array ที่เป็นตัวเลข (Matrix)

Num+py -> Number-Numeracal + python

ขั้นตอนการใช้ package

1.```import``` ```ชื่อpackage``` #เรียกใช้package

2.```ชื่อpackage```.```ชื่อฟังก์ชัน``` #เรียกใช่ฟังก์ชั่น

In [52]:
import numpy

สร้าง array (numpy array)

In [54]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


ชี้ค่าใน numpy array

In [55]:
mat_ex1[1,1] #[แถว,หลัก]

0.1

ถ้าไม่มี numpy array

In [ ]:
list_ex1 = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
print (list_ex1)

In [ ]:
list_ex1[1][1]

In [ ]:
print (list_ex1)
a = list_ex1[1]
print (a)
print (a[1])

Matrix Operation

data 2 แบบ -> matrix (2D array) , scalar (ตัวเลขค่าคงที่)

In [56]:
mat_ex1 = numpy.array ([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print (mat_ex1)
mat_ex2 = numpy.array ([[2,3.7,5.9],[91,1.5,7.3]])
print (mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


บวกกับลบ matrix เอาตัวเลขตำแหน่งเดียวกันมาบวกหรือลบกัน

ตรวจสอบขนาดของ matrix

In [ ]:
mat_ex3.shap